Delete product-scenarios/2-Bridging-systems-that-communicate-in-different-protocols directory
delete product-scenarios/
2-Bridging-systems-that-communicate-in-different-protocols
because occur git checkout branch error 
error: The following untracked working tree files would be overwritten by checkout:
        product-scenarios/2-Bridging-systems-that-communicate-in-different-protocols/2.7-FTP-transport-listener-to-mail-transport-sender./2.7.1-vfs-transport-invocation/readme.md
        product-scenarios/2-Bridging-systems-that-communicate-in-different-protocols/2.7-FTP-transport-listener-to-mail-transport-sender./readme.md
Please move or remove them before you switch branches.
Aborting